# Generated by Django 3.0.7 on 2020-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_info_form',
            name='backimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
