# Generated by Django 3.0.7 on 2020-07-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_all_info_form_backimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_info_form',
            name='backimage',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='date',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='email',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='image',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='name',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='all_info_form',
            name='town_name',
        ),
        migrations.AddField(
            model_name='all_info_form',
            name='backpic',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='all_info_form',
            name='pic',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
